### ISSUE TITLE
Fail to execute it via serverSHARK

### ISSUE THREAD

**Issue by yiikou** [smartshark/refSHARK#3]
Hi, when I tried to execute refSHARK for java project `junit4`, I got an error `ERROR: Unrecognized option: --project_name`.
Here is my argument 
![image](https://user-images.githubusercontent.com/6872777/98629204-5ba08100-22e6-11eb-8afe-494a60aa6458.png).

How should I execute it using serverSHARK? And is it able to visualize the result in the visualSHARK?

Thank you.

**Comment by sherbold** [comment]
The hacky fix would be to remove the --project_name from the exucute.sh in the folder where the plug-in is installed on the servershark - that is also our current solution. 

We will provide a fixed version of the refSHARK in the next couple of days that correctly uses the project_name.

**Comment by yiikou** [comment]
Hi, @sherbold. Thanks for the solution and this hacky way works. Here is an example of data from refactoring collection in mongodb:
![image](https://user-images.githubusercontent.com/6872777/98819774-4b2dfa80-23fb-11eb-8124-93d5b655305d.png)
Does the plugin do work in my case?

Thank you.

**Comment by sherbold** [comment]
Yes, that looks correct. By the way, we just saw that our second refactoring collection plugin is still in a private repository and we forgot to move that public. The difference between the two is that this one uses refDiff, the other one uses RefactoringMiner. So if you see the repository rMinerShark in the next couple of days, that does the refactoring mining with RefactoringMiner.

**Comment by yiikou** [comment]
Btw, can refactoring result be visualized in visualSHARK?
